language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - nightly

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose
